version: "3"

services:
  # -----------------------
  # - web container
  # -----------------------
  web:
    build: ./web
    volumes:
      - ./static:/app/static
    ports:
      - "8000:80"
    depends_on:
      - app

  # -----------------------
  # - application container
  # -----------------------
  app:
    image: ghcr.io/nazarhanov/alpha:latest
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             gunicorn alpha.wsgi:application --bind 0.0.0.0:8000"
    env_file: ./app/.env.app
    volumes:
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy

  # -----------------------
  # - database container
  # -----------------------
  db:
    build: ./db
    env_file: ./db/.env.db
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1s
      timeout: 20s
      retries: 12

  # -----------------------
  # - watch container
  # -----------------------
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /$HOME/.docker/config.json:/config.json
    command: --interval 30
    environment:
      - WATCHTOWER_CLEANUP=true
